name: Mod Build

on:
  push:
    branches: [ "C-M-Y" ]
  pull_request:
    branches: [ "C-M-Y" ]
  workflow_dispatch:

jobs:
  try_to_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
            ndk-version: r26b
      - name: Change VersionName to Nightly Version
        run: sed -i 's/\(versionCode=".*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})"/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')"/' mod/source/module.prop
      - name: Build Mod
        run: |
          cd mod/jni ; ndk-build ; cd ../ ; mkdir -p source/bin ; cp -rf libs/arm64-v8a source/bin/arm64 ; cp -rf libs/armeabi-v7a source/bin/arm ; cp -rf libs/x86_64 source/bin/x86_64 ; cp -rf libs/x86 source/bin/x86
          cp -rf encrypt/cmd.sh encrypt.sh ; chmod 0777 busybox ; ./busybox dos2unix encrypt.sh ; ./busybox sh encrypt.sh overfiles 3 source ; sh verify.sh ; cp -rf ../README.md source/README.md ; cp -rf changelog.md source/changelog.md ; sh changeTime.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CacheCleaner-Mod
          path: mod/source